{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews.prod.svc.cluster.local
  http:
  - name: "reviews-v2-routes"
    match:
    - uri:
        prefix: "/api/"
    rewrite:
      uri: "/api/"
    route:
    - destination:
        host: {{ include "k8s-app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ $.Values.service.port }}
{{- end }}
